# Generated by Django 5.2.1 on 2025-08-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
    ]
