# Generated by Django 5.2.1 on 2025-08-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_description'),
        ('liga', '0003_alter_liga_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='liga',
        ),
        migrations.AddField(
            model_name='event',
            name='ligas',
            field=models.ManyToManyField(blank=True, to='liga.liga'),
        ),
    ]
