# Generated by Django 5.2.1 on 2025-08-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_liga_event_ligas'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='open_to_reservations',
            field=models.BooleanField(default=True),
        ),
    ]
