# Generated by Django 5.2.1 on 2025-09-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_end_date_remove_event_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time']},
        ),
    ]
