# Generated by Django 5.2.1 on 2025-09-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='open_to_reservations',
            field=models.BooleanField(default=False),
        ),
    ]
