# Generated by Django 5.2.1 on 2025-08-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_is_canceled_event_open_to_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='event_images'),
        ),
    ]
