# Generated by Django 5.2.1 on 2025-10-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_open_to_reservations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
