# Generated by Django 5.2.1 on 2025-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reservations_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of reservations allowed. Leave blank for no limit.', null=True),
        ),
    ]
