# Generated by Django 5.2.1 on 2025-10-11 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_reservations_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reservations_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of reservations allowed. Leave blank for no limit.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
