# Generated by Django 5.2.1 on 2025-08-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ligas_images'),
        ),
    ]
