# Generated by Django 5.2.1 on 2025-08-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_liga_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
