# Generated by Django 5.2.1 on 2025-09-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default=None, help_text='Unique username', max_length=255, unique=True),
        ),
    ]
