# Generated by Django 5.2.1 on 2025-10-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_email_alter_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='born_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
