# Generated by Django 5.2.1 on 2025-12-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['created_at']},
        ),
    ]
