# Generated by Django 5.2.1 on 2026-01-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='timezone',
        ),
    ]
