# Generated by Django 5.2.1 on 2025-09-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchgroup',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
