# Generated by Django 5.2.1 on 2025-10-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
